import type { NextPage } from 'next'
import Head from 'next/head'

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Title</title>
        <meta name='description' content='Generated by create next app' />
      </Head>

      <div>
        <h1>Hello Next.js</h1>
      </div>
    </>
  )
}

export default Home
